/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Benji' at '7/3/16 8:08 PM' with Gradle 2.10
 *
 * @author Benji, @date 7/3/16 8:08 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
